# Generated by Django 5.1 on 2024-09-09 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('taxonid', models.IntegerField(primary_key=True, serialize=False)),
                ('kingdom_name', models.CharField(max_length=100)),
                ('phylum_name', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=100)),
                ('order_name', models.CharField(max_length=100)),
                ('family_name', models.CharField(max_length=100)),
                ('genus_name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(max_length=255)),
                ('taxonomic_authority', models.CharField(max_length=255)),
                ('infra_rank', models.CharField(blank=True, max_length=100, null=True)),
                ('infra_name', models.CharField(blank=True, max_length=100, null=True)),
                ('population', models.TextField(blank=True, null=True)),
                ('category', models.CharField(max_length=50)),
                ('main_common_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'species',
                'managed': False,
            },
        ),
    ]
