# Generated by Django 5.1 on 2024-09-23 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_user_bio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='species',
            options={},
        ),
    ]
