# Generated by Django 5.1 on 2024-09-23 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_species_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='species',
            table=None,
        ),
    ]
