# Generated by Django 5.1 on 2024-09-23 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_species_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='species',
            table='species',
        ),
    ]
