# Generated by Django 5.1 on 2024-09-28 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_species_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='species',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
